apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: device-plugin-demo
  namespace: default
  labels:
    app: device-plugin-demo
spec:
  selector:
    matchLabels:
      app: device-plugin-demo
  template:
    metadata:
      labels:
        app: device-plugin-demo
    spec:
      containers:
        - name: device-plugin-demo
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: mydevice
              mountPath: /etc/mydevice
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: mydevice
          hostPath:
            path: /etc/mydevice